# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\dynam\Documents\rps-multiplayer\client\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1044, 845)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        MainWindow.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("QWidget#centralwidget {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0.269663 rgba(85, 170, 127, 255), stop:1 rgba(255, 255, 255, 255))\n"
"}\n"
"\n"
"QLabel#label {\n"
"    min-height: 5em\n"
"}\n"
"\n"
"QLabel#label_2, QLabel#rounds {\n"
"    min-height: 5em;\n"
"    margin: 5% 10%;\n"
"}\n"
"\n"
"QLabel#p1label {\n"
"    min-height: 4em;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-radius: 6px;\n"
"    border-color: blue\n"
"}\n"
"\n"
"QLabel#p1Points {\n"
"    min-height: 9em;\n"
"    background-color: lightblue;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-radius: 6px;\n"
"    border-color: blue\n"
"}\n"
"\n"
"QLabel#p2label {\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-radius: 6px;\n"
"    border-color: red\n"
"}\n"
"\n"
"QLabel#p2Points {\n"
"    background-color: rgb(255, 125, 145);\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-radius: 6px;\n"
"    border-color: red\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: lightgrey;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 6px;\n"
"    border-color: grey;\n"
"      min-height: 20px;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QPushButton#pb_close{\n"
"    margin: 7% 40%\n"
"}\n"
"\n"
"QPushButton#pb_reset{\n"
"    margin: 7% 40%\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0.006, y1:0.915182, x2:0, y2:0, stop:0.0798991 rgba(195,195,195,255), stop:0.330322 rgba(203,203,203,255), stop:1 rgba (255,255,255,255));\n"
"    border-color: rgb(45, 45, 45);\n"
"    border-style: inset;\n"
"}\n"
"\n"
"QComboBox {\n"
"    border: 1px solid gray;\n"
"    border-radius: 6px;\n"
"    padding: 1px 18px 1px 3px;\n"
"    min-height: 2em;\n"
"    min-width: 6em;\n"
"}\n"
"\n"
"QComboBox:editable {\n"
"    background: white;\n"
"}\n"
"\n"
"QComboBox:!editable, QComboBox::drop-down:editable {\n"
"     background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #E1E1E1, stop: 0.4 #DDDDDD,\n"
"                                 stop: 0.5 #D8D8D8, stop: 1.0 #D3D3D3);\n"
"}\n"
"\n"
"/* QComboBox gets the \"on\" state when the popup is open */\n"
"QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #D3D3D3, stop: 0.4 #D8D8D8,\n"
"                                stop: 0.5 #DDDDDD, stop: 1.0 #E1E1E1);\n"
"}\n"
"\n"
"QComboBox:on { /* shift the text when the popup opens */\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 15px;\n"
"\n"
"    border-left-width: 1px;\n"
"    border-left-color: darkgray;\n"
"    border-left-style: solid; /* just a single line */\n"
"    border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(d:/Schule/5BHIT/SEW/RockPaperScissors/icons/arrow.png);\n"
"}\n"
"\n"
"QComboBox::down-arrow:on { /* shift the arrow when popup is open */\n"
"    top: 1px;\n"
"    left: 1px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        palette = QtGui.QPalette()
        gradient = QtGui.QLinearGradient(0.0, 0.0, 0.0, 1.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.269663, QtGui.QColor(85, 170, 127))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 0.0, 1.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.269663, QtGui.QColor(85, 170, 127))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 0.0, 1.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.269663, QtGui.QColor(85, 170, 127))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 0.0, 1.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.269663, QtGui.QColor(85, 170, 127))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 0.0, 1.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.269663, QtGui.QColor(85, 170, 127))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 0.0, 1.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.269663, QtGui.QColor(85, 170, 127))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 0.0, 1.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.269663, QtGui.QColor(85, 170, 127))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 0.0, 1.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.269663, QtGui.QColor(85, 170, 127))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 0.0, 1.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.269663, QtGui.QColor(85, 170, 127))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.centralwidget.setPalette(palette)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.rounds = QtWidgets.QLabel(self.centralwidget)
        self.rounds.setFrameShape(QtWidgets.QFrame.Box)
        self.rounds.setAlignment(QtCore.Qt.AlignCenter)
        self.rounds.setObjectName("rounds")
        self.horizontalLayout.addWidget(self.rounds)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.p1Choice = QtWidgets.QGraphicsView(self.centralwidget)
        self.p1Choice.setObjectName("p1Choice")
        self.horizontalLayout_3.addWidget(self.p1Choice)
        self.p2Choice = QtWidgets.QGraphicsView(self.centralwidget)
        self.p2Choice.setEnabled(True)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.p2Choice.setBackgroundBrush(brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.DiagCrossPattern)
        self.p2Choice.setForegroundBrush(brush)
        self.p2Choice.setObjectName("p2Choice")
        self.horizontalLayout_3.addWidget(self.p2Choice)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.p2label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.p2label.setFont(font)
        self.p2label.setFrameShape(QtWidgets.QFrame.Box)
        self.p2label.setAlignment(QtCore.Qt.AlignCenter)
        self.p2label.setObjectName("p2label")
        self.gridLayout.addWidget(self.p2label, 1, 2, 1, 1)
        self.pb_exec = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.pb_exec.setFont(font)
        self.pb_exec.setToolTipDuration(5000)
        self.pb_exec.setObjectName("pb_exec")
        self.gridLayout.addWidget(self.pb_exec, 3, 2, 1, 1)
        self.p1label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.p1label.setFont(font)
        self.p1label.setFrameShape(QtWidgets.QFrame.Box)
        self.p1label.setAlignment(QtCore.Qt.AlignCenter)
        self.p1label.setObjectName("p1label")
        self.gridLayout.addWidget(self.p1label, 1, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setToolTipDuration(5000)
        self.comboBox.setWhatsThis("")
        self.comboBox.setObjectName("comboBox")
        self.gridLayout.addWidget(self.comboBox, 3, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setFrameShape(QtWidgets.QFrame.Box)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 3, 0, 1, 1)
        self.p1Points = QtWidgets.QLabel(self.centralwidget)
        self.p1Points.setFrameShape(QtWidgets.QFrame.Box)
        self.p1Points.setAlignment(QtCore.Qt.AlignCenter)
        self.p1Points.setObjectName("p1Points")
        self.gridLayout.addWidget(self.p1Points, 2, 0, 1, 1)
        self.p2Points = QtWidgets.QLabel(self.centralwidget)
        self.p2Points.setFrameShape(QtWidgets.QFrame.Box)
        self.p2Points.setAlignment(QtCore.Qt.AlignCenter)
        self.p2Points.setObjectName("p2Points")
        self.gridLayout.addWidget(self.p2Points, 2, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pb_reset = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.pb_reset.setFont(font)
        self.pb_reset.setObjectName("pb_reset")
        self.horizontalLayout_2.addWidget(self.pb_reset)
        self.pb_close = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.pb_close.setFont(font)
        self.pb_close.setObjectName("pb_close")
        self.horizontalLayout_2.addWidget(self.pb_close)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1044, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pb_close.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Schere Stein Papier"))
        self.label.setText(_translate("MainWindow", " Aktueller Spielstand"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt;\">Aktuelle Runde</span></p></body></html>"))
        self.rounds.setText(_translate("MainWindow", "0"))
        self.p2label.setText(_translate("MainWindow", "Player 2"))
        self.pb_exec.setToolTip(_translate("MainWindow", "<html><head/><body><p>Zug ausführen</p></body></html>"))
        self.pb_exec.setText(_translate("MainWindow", "Ausführen"))
        self.p1label.setText(_translate("MainWindow", "Player 1"))
        self.comboBox.setToolTip(_translate("MainWindow", "<html><head/><body><p>Wähle einen Spielzug aus:</p><p>0 ... Schere</p><p>1 ... Stein</p><p>2 ... Papier</p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "Spielzug"))
        self.p1Points.setText(_translate("MainWindow", "0"))
        self.p2Points.setText(_translate("MainWindow", "0"))
        self.pb_reset.setText(_translate("MainWindow", "Zurücksetzen"))
        self.pb_close.setText(_translate("MainWindow", "Schließen"))
